// Package monitoring provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for ComponentActionAction.
const (
	ComponentActionActionInstall   ComponentActionAction = "install"
	ComponentActionActionReinstall ComponentActionAction = "reinstall"
	ComponentActionActionRepair    ComponentActionAction = "repair"
	ComponentActionActionSkip      ComponentActionAction = "skip"
	ComponentActionActionUpgrade   ComponentActionAction = "upgrade"
)

// Defines values for ComponentName.
const (
	Alertmanager     ComponentName = "alertmanager"
	BlackboxExporter ComponentName = "blackbox-exporter"
	Grafana          ComponentName = "grafana"
	KubeStateMetrics ComponentName = "kube-state-metrics"
	NodeExporter     ComponentName = "node-exporter"
	Prometheus       ComponentName = "prometheus"
	Thanos           ComponentName = "thanos"
)

// Defines values for ComponentPhase.
const (
	ComponentPhaseFailed           ComponentPhase = "Failed"
	ComponentPhaseHealthy          ComponentPhase = "Healthy"
	ComponentPhaseInstalling       ComponentPhase = "Installing"
	ComponentPhaseNotInstalled     ComponentPhase = "NotInstalled"
	ComponentPhasePlanned          ComponentPhase = "Planned"
	ComponentPhaseUnhealthy        ComponentPhase = "Unhealthy"
	ComponentPhaseUpgradeAvailable ComponentPhase = "UpgradeAvailable"
	ComponentPhaseVerifyingHealth  ComponentPhase = "VerifyingHealth"
)

// Defines values for CreatePlanRequestIntent.
const (
	CreatePlanRequestIntentInstall CreatePlanRequestIntent = "install"
	CreatePlanRequestIntentRepair  CreatePlanRequestIntent = "repair"
	CreatePlanRequestIntentUpgrade CreatePlanRequestIntent = "upgrade"
)

// Defines values for DiagnosisSeverity.
const (
	Critical DiagnosisSeverity = "critical"
	Major    DiagnosisSeverity = "major"
	Minor    DiagnosisSeverity = "minor"
)

// Defines values for ExecutionStepAction.
const (
	ExecutionStepActionCleanup ExecutionStepAction = "cleanup"
	ExecutionStepActionInstall ExecutionStepAction = "install"
	ExecutionStepActionRepair  ExecutionStepAction = "repair"
	ExecutionStepActionUpgrade ExecutionStepAction = "upgrade"
	ExecutionStepActionVerify  ExecutionStepAction = "verify"
)

// Defines values for ExecutionStepStatus.
const (
	ExecutionStepStatusFailed    ExecutionStepStatus = "failed"
	ExecutionStepStatusPending   ExecutionStepStatus = "pending"
	ExecutionStepStatusRunning   ExecutionStepStatus = "running"
	ExecutionStepStatusSkipped   ExecutionStepStatus = "skipped"
	ExecutionStepStatusSucceeded ExecutionStepStatus = "succeeded"
)

// Defines values for FailureCategory.
const (
	Configuration FailureCategory = "Configuration"
	Dependency    FailureCategory = "Dependency"
	HelmChart     FailureCategory = "HelmChart"
	ImagePull     FailureCategory = "ImagePull"
	NetworkPolicy FailureCategory = "NetworkPolicy"
	RBAC          FailureCategory = "RBAC"
	ResourceQuota FailureCategory = "ResourceQuota"
	StorageClass  FailureCategory = "StorageClass"
	Timeout       FailureCategory = "Timeout"
	Unknown       FailureCategory = "Unknown"
)

// Defines values for InstallConfigInstallMode.
const (
	Assisted InstallConfigInstallMode = "assisted"
	Byo      InstallConfigInstallMode = "byo"
	Managed  InstallConfigInstallMode = "managed"
)

// Defines values for InstallPhase.
const (
	Active       InstallPhase = "Active"
	Degraded     InstallPhase = "Degraded"
	Detecting    InstallPhase = "Detecting"
	Failed       InstallPhase = "Failed"
	Installing   InstallPhase = "Installing"
	NotStarted   InstallPhase = "NotStarted"
	Planning     InstallPhase = "Planning"
	Uninstalling InstallPhase = "Uninstalling"
	Upgrading    InstallPhase = "Upgrading"
	Verifying    InstallPhase = "Verifying"
)

// Defines values for InstallationPlanRiskLevel.
const (
	High   InstallationPlanRiskLevel = "high"
	Low    InstallationPlanRiskLevel = "low"
	Medium InstallationPlanRiskLevel = "medium"
)

// Defines values for PlanStepAction.
const (
	PlanStepActionInstall   PlanStepAction = "install"
	PlanStepActionRepair    PlanStepAction = "repair"
	PlanStepActionUninstall PlanStepAction = "uninstall"
	PlanStepActionUpgrade   PlanStepAction = "upgrade"
	PlanStepActionVerify    PlanStepAction = "verify"
)

// Defines values for RetryRequestMode.
const (
	Automatic RetryRequestMode = "automatic"
	Manual    RetryRequestMode = "manual"
)

// Defines values for RetryStatusMode.
const (
	Exhausted RetryStatusMode = "exhausted"
	Idle      RetryStatusMode = "idle"
	Running   RetryStatusMode = "running"
	Scheduled RetryStatusMode = "scheduled"
)

// Defines values for SessionTemplateIntent.
const (
	Install SessionTemplateIntent = "install"
	Repair  SessionTemplateIntent = "repair"
	Upgrade SessionTemplateIntent = "upgrade"
)

// AutoFix defines model for AutoFix.
type AutoFix struct {
	Automated    bool    `json:"automated"`
	Description  *string `json:"description,omitempty"`
	Id           string  `json:"id"`
	Title        string  `json:"title"`
	Verification *string `json:"verification,omitempty"`
}

// AutoFixRequest defines model for AutoFixRequest.
type AutoFixRequest struct {
	Context   *map[string]string `json:"context,omitempty"`
	FixId     string             `json:"fixId"`
	SessionId string             `json:"sessionId"`
}

// AutoFixResponse defines model for AutoFixResponse.
type AutoFixResponse struct {
	FollowupStep *ExecutionStep `json:"followupStep,omitempty"`
	Message      *string        `json:"message,omitempty"`
	Success      bool           `json:"success"`
}

// Checkpoint defines model for Checkpoint.
type Checkpoint struct {
	CompletedSteps *[]int            `json:"completedSteps,omitempty"`
	Components     *[]ComponentState `json:"components,omitempty"`

	// Config User provided options from the wizard.
	Config        *InstallConfig     `json:"config,omitempty"`
	Context       *map[string]string `json:"context,omitempty"`
	CurrentStep   *int               `json:"currentStep,omitempty"`
	Errors        *[]InstallError    `json:"errors,omitempty"`
	LastUpdatedAt *time.Time         `json:"lastUpdatedAt,omitempty"`
	Phase         *InstallPhase      `json:"phase,omitempty"`
	Progress      *float32           `json:"progress,omitempty"`
	SessionId     *string            `json:"sessionId,omitempty"`
	StartedAt     *time.Time         `json:"startedAt,omitempty"`
}

// ComponentAction defines model for ComponentAction.
type ComponentAction struct {
	Action ComponentActionAction `json:"action"`
	Reason string                `json:"reason"`
}

// ComponentActionAction defines model for ComponentAction.Action.
type ComponentActionAction string

// ComponentName defines model for ComponentName.
type ComponentName string

// ComponentPhase defines model for ComponentPhase.
type ComponentPhase string

// ComponentState defines model for ComponentState.
type ComponentState struct {
	ErrorMessage *string        `json:"errorMessage,omitempty"`
	Healthy      *bool          `json:"healthy,omitempty"`
	InstalledAt  *time.Time     `json:"installedAt,omitempty"`
	LastCheckAt  *time.Time     `json:"lastCheckAt,omitempty"`
	MaxRetries   *int32         `json:"maxRetries,omitempty"`
	Name         ComponentName  `json:"name"`
	Phase        ComponentPhase `json:"phase"`
	RetryCount   *int32         `json:"retryCount,omitempty"`
	Version      *string        `json:"version,omitempty"`
}

// CreatePlanRequest defines model for CreatePlanRequest.
type CreatePlanRequest struct {
	// Config User provided options from the wizard.
	Config InstallConfig `json:"config"`

	// Detected Snapshot of existing monitoring components and prerequisites.
	Detected EnvironmentSnapshot      `json:"detected"`
	Intent   *CreatePlanRequestIntent `json:"intent,omitempty"`
}

// CreatePlanRequestIntent defines model for CreatePlanRequest.Intent.
type CreatePlanRequestIntent string

// CreatePlanResponse defines model for CreatePlanResponse.
type CreatePlanResponse struct {
	EstimatedDurationSeconds int64            `json:"estimatedDurationSeconds"`
	Plan                     InstallationPlan `json:"plan"`
	Warnings                 *[]string        `json:"warnings,omitempty"`
}

// DetectedComponent defines model for DetectedComponent.
type DetectedComponent struct {
	ActionRecommendation ComponentAction    `json:"actionRecommendation"`
	Details              *map[string]string `json:"details,omitempty"`
	Exists               *bool              `json:"exists,omitempty"`
	Healthy              *bool              `json:"healthy,omitempty"`
	Name                 ComponentName      `json:"name"`
	Version              *string            `json:"version,omitempty"`
}

// DiagnoseRequest defines model for DiagnoseRequest.
type DiagnoseRequest struct {
	Context *map[string]string `json:"context,omitempty"`
	Error   InstallError       `json:"error"`
}

// DiagnoseResponse defines model for DiagnoseResponse.
type DiagnoseResponse struct {
	AutoFixes *[]AutoFix `json:"autoFixes,omitempty"`
	Diagnosis Diagnosis  `json:"diagnosis"`
}

// Diagnosis defines model for Diagnosis.
type Diagnosis struct {
	Category       FailureCategory   `json:"category"`
	PossibleCauses *[]string         `json:"possibleCauses,omitempty"`
	Severity       DiagnosisSeverity `json:"severity"`
	SuggestedFixes *[]string         `json:"suggestedFixes,omitempty"`
	Summary        string            `json:"summary"`
}

// DiagnosisSeverity defines model for Diagnosis.Severity.
type DiagnosisSeverity string

// EnvironmentSnapshot Snapshot of existing monitoring components and prerequisites.
type EnvironmentSnapshot struct {
	Components []DetectedComponent `json:"components"`
	DetectedAt time.Time           `json:"detectedAt"`

	// HealthScore Aggregate health score averaged from component status.
	HealthScore *int32 `json:"healthScore,omitempty"`

	// Namespace Target namespace where monitoring stack resides.
	Namespace string `json:"namespace"`

	// Recommendations Suggested follow-up actions before installation.
	Recommendations *[]string `json:"recommendations,omitempty"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Defines values for ErrorCode.
const (
	ErrorCodeAutofixContextFailed  ErrorCode = "monitoring/autofix-context-failed"
	ErrorCodeAutofixFailed         ErrorCode = "monitoring/autofix-failed"
	ErrorCodeAutofixInvalid        ErrorCode = "monitoring/autofix-invalid"
	ErrorCodeDetectFailed          ErrorCode = "monitoring/detect-failed"
	ErrorCodeDetectUnavailable     ErrorCode = "monitoring/detect-unavailable"
	ErrorCodeDiagnoseContextFailed ErrorCode = "monitoring/diagnose-context-failed"
	ErrorCodeDiagnoseFailed        ErrorCode = "monitoring/diagnose-failed"
	ErrorCodeDiagnoseInvalid       ErrorCode = "monitoring/diagnose-invalid"
	ErrorCodeInstallInvalidRequest ErrorCode = "monitoring/install-invalid-request"
	ErrorCodeInstallPlanEmpty      ErrorCode = "monitoring/install-plan-empty"
	ErrorCodeK8sClientMissing      ErrorCode = "monitoring/k8s-client-missing"
	ErrorCodePlanInvalid           ErrorCode = "monitoring/plan-invalid"
	ErrorCodeRetryActivateFailed   ErrorCode = "monitoring/retry-activate-failed"
	ErrorCodeRetryInvalidMode      ErrorCode = "monitoring/retry-invalid-mode"
	ErrorCodeRetryInvalidRequest   ErrorCode = "monitoring/retry-invalid-request"
	ErrorCodeRetryLimitReached     ErrorCode = "monitoring/retry-limit-reached"
	ErrorCodeRetryPersistFailed    ErrorCode = "monitoring/retry-persist-failed"
	ErrorCodeRetryStartFailed      ErrorCode = "monitoring/retry-start-failed"
	ErrorCodeRetryUnavailable      ErrorCode = "monitoring/retry-unavailable"
	ErrorCodeSessionCreateFailed   ErrorCode = "monitoring/session-create-failed"
	ErrorCodeSessionNotFound       ErrorCode = "monitoring/session-not-found"
	ErrorCodeSessionPersistFailed  ErrorCode = "monitoring/session-persist-failed"
	ErrorCodeSessionRequired       ErrorCode = "monitoring/session-required"
	ErrorCodeSessionRestoreFailed  ErrorCode = "monitoring/session-restore-failed"
	ErrorCodeUnknownError          ErrorCode = "monitoring/unknown-error"
)

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    *ErrorCode         `json:"code,omitempty"`
	Details *map[string]string `json:"details,omitempty"`
	Message string             `json:"message"`
}

// ExecutionStep defines model for ExecutionStep.
type ExecutionStep struct {
	Action      ExecutionStepAction `json:"action"`
	CompletedAt *time.Time          `json:"completedAt,omitempty"`
	Component   ComponentName       `json:"component"`
	Message     *string             `json:"message,omitempty"`
	Order       int32               `json:"order"`
	StartedAt   *time.Time          `json:"startedAt,omitempty"`
	Status      ExecutionStepStatus `json:"status"`
}

// ExecutionStepAction defines model for ExecutionStep.Action.
type ExecutionStepAction string

// ExecutionStepStatus defines model for ExecutionStep.Status.
type ExecutionStepStatus string

// FailureCategory defines model for FailureCategory.
type FailureCategory string

// InstallConfig User provided options from the wizard.
type InstallConfig struct {
	AutoRepair      *bool                     `json:"autoRepair,omitempty"`
	InstallMode     *InstallConfigInstallMode `json:"installMode,omitempty"`
	TargetNamespace *string                   `json:"targetNamespace,omitempty"`

	// ValuesYaml Raw Helm values override provided by the user.
	ValuesYaml *string `json:"valuesYaml,omitempty"`
}

// InstallConfigInstallMode defines model for InstallConfig.InstallMode.
type InstallConfigInstallMode string

// InstallError defines model for InstallError.
type InstallError struct {
	Category   FailureCategory    `json:"category"`
	Component  *ComponentName     `json:"component,omitempty"`
	Context    *map[string]string `json:"context,omitempty"`
	Message    string             `json:"message"`
	OccurredAt *time.Time         `json:"occurredAt,omitempty"`
	StepOrder  *int32             `json:"stepOrder,omitempty"`
}

// InstallPhase defines model for InstallPhase.
type InstallPhase string

// InstallStatusResponse defines model for InstallStatusResponse.
type InstallStatusResponse struct {
	Checkpoint     *Checkpoint      `json:"checkpoint,omitempty"`
	CompletedSteps *[]ExecutionStep `json:"completedSteps,omitempty"`
	Components     []ComponentState `json:"components"`
	CurrentStep    *ExecutionStep   `json:"currentStep,omitempty"`
	Errors         *[]InstallError  `json:"errors,omitempty"`
	Phase          InstallPhase     `json:"phase"`
	Progress       *float32         `json:"progress,omitempty"`
	Retry          *RetryStatus     `json:"retry,omitempty"`
	SessionId      string           `json:"sessionId"`
	StartedAt      *time.Time       `json:"startedAt,omitempty"`
	UpdatedAt      time.Time        `json:"updatedAt"`
}

// InstallationPlan defines model for InstallationPlan.
type InstallationPlan struct {
	EstimatedDurationSeconds *int64                     `json:"estimatedDurationSeconds,omitempty"`
	RiskLevel                *InstallationPlanRiskLevel `json:"riskLevel,omitempty"`
	SessionTemplate          SessionTemplate            `json:"sessionTemplate"`
	Steps                    []PlanStep                 `json:"steps"`
}

// InstallationPlanRiskLevel defines model for InstallationPlan.RiskLevel.
type InstallationPlanRiskLevel string

// PlanStep defines model for PlanStep.
type PlanStep struct {
	Action    PlanStepAction `json:"action"`
	Component ComponentName  `json:"component"`

	// DependsOn Orders that must be completed first.
	DependsOn                *[]int  `json:"dependsOn,omitempty"`
	EstimatedDurationSeconds *int64  `json:"estimatedDurationSeconds,omitempty"`
	Order                    int32   `json:"order"`
	Reason                   *string `json:"reason,omitempty"`
}

// PlanStepAction defines model for PlanStep.Action.
type PlanStepAction string

// RetryRequest defines model for RetryRequest.
type RetryRequest struct {
	// Force Force retry even if automatic retries are exhausted.
	Force *bool `json:"force,omitempty"`

	// Mode Desired retry mode; omit to use default behaviour.
	Mode *RetryRequestMode `json:"mode,omitempty"`

	// Reason Optional reason recorded for audit purposes.
	Reason *string `json:"reason,omitempty"`
}

// RetryRequestMode Desired retry mode; omit to use default behaviour.
type RetryRequestMode string

// RetryStatus defines model for RetryStatus.
type RetryStatus struct {
	// Active Indicates whether an automatic retry is currently scheduled.
	Active *bool `json:"active,omitempty"`

	// BackoffSeconds Current backoff delay in seconds before the next retry.
	BackoffSeconds *int64 `json:"backoffSeconds,omitempty"`

	// LastAttemptAt Timestamp when the most recent retry attempt started.
	LastAttemptAt *time.Time `json:"lastAttemptAt,omitempty"`

	// LastError Last failure message that triggered a retry.
	LastError *string `json:"lastError,omitempty"`

	// MaxRetries Maximum number of retry attempts permitted.
	MaxRetries *int32           `json:"maxRetries,omitempty"`
	Mode       *RetryStatusMode `json:"mode,omitempty"`

	// NextRetryAt Timestamp when the next automatic retry will be triggered.
	NextRetryAt *time.Time `json:"nextRetryAt,omitempty"`

	// Retries Number of retry attempts already executed.
	Retries *int32 `json:"retries,omitempty"`
}

// RetryStatusMode defines model for RetryStatusMode.
type RetryStatusMode string

// SessionTemplate defines model for SessionTemplate.
type SessionTemplate struct {
	Intent          *SessionTemplateIntent `json:"intent,omitempty"`
	Namespace       string                 `json:"namespace"`
	ReleaseName     *string                `json:"releaseName,omitempty"`
	TargetNamespace *string                `json:"targetNamespace,omitempty"`
}

// SessionTemplateIntent defines model for SessionTemplate.Intent.
type SessionTemplateIntent string

// StartInstallRequest defines model for StartInstallRequest.
type StartInstallRequest struct {
	Checkpoint *Checkpoint      `json:"checkpoint,omitempty"`
	Plan       InstallationPlan `json:"plan"`
}

// StartInstallResponse defines model for StartInstallResponse.
type StartInstallResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	JobName   *string   `json:"jobName,omitempty"`
	Namespace string    `json:"namespace"`

	// Resumed Indicates whether existing execution was resumed from checkpoint.
	Resumed   *bool  `json:"resumed,omitempty"`
	SessionId string `json:"sessionId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorBody

// ApplyAutoFixJSONRequestBody defines body for ApplyAutoFix for application/json ContentType.
type ApplyAutoFixJSONRequestBody = AutoFixRequest

// DiagnoseFailureJSONRequestBody defines body for DiagnoseFailure for application/json ContentType.
type DiagnoseFailureJSONRequestBody = DiagnoseRequest

// StartInstallationJSONRequestBody defines body for StartInstallation for application/json ContentType.
type StartInstallationJSONRequestBody = StartInstallRequest

// TriggerRetryJSONRequestBody defines body for TriggerRetry for application/json ContentType.
type TriggerRetryJSONRequestBody = RetryRequest

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = CreatePlanRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xbS3PcuPH/Kij8/0fqsd6tHJSTLGUTV629imSnktr1AUM2ObBIgIvHPOKa755qAHxj",
	"ZjjyyMmN4oBAv/vX3dBXmsqqlgKE0fTmK1Wgayk0uD/+opRUj+ENvkilMCAMPrK6LnnKDJfi6ouWAt/p",
	"dAkVw6f/V5DTG/p/V93uV/5XfeV2fSuzLd3tdgnNQKeK17gRvfFHkoYKAmIFpayB4sqwAe5/a438mW/w",
	"sVayBmW4J5lZIytmIMM/zLYGekMXUpbABB0f1i7QRnFR4O88i7423JQQ/WUFiudBDpEFu4Qq+MNyhQT9",
	"hts3myU9Uj8nzXdy8QVSgxsHDh/hDwvaTBl1qth4VWQZx/NZ+TBYMmVjfEjON+/iHGvQmksR/XXElN+k",
	"/8lBfjprGjKUy7KUa1s/GaiPmtAGUossu8W7hFagNSviKtI2TUHrmEGMOGlWxui/W0L6XEsuorqo6hIM",
	"ZEiOe8MNVP0TuTBQgOopgSnFtvj30P/aDw+xf9e8ejLMQHxTkfPi2D7vhDasLO/8Yv/ZtxtVapVytHk9",
	"TiUA6OPzuQ1UusgQ47Vk2nyqM/SkW+MtSVXM0BuK7y4Mr9DbJnTXS+bNcMbZD24tfqRkoYIxtcfkpWSG",
	"JrRiG17Zit78kNCKC/983R4tbLXwAjjkXAnVhqmTeIkpoTWR27QJTaNA2b4HgXT+RrnnlSbU1oViGZ6k",
	"oGZcuYfuZ/3M656PdJQrYHpOGAxntx98PsTAB1ZBn8xayQrMEqymCS0Uy5lgGE1LUKZigqGRJVTIDC5g",
	"U0tl3N/PdgEXGt3logKjeIpfmyUTEh8WJUufF3LTfRFjryXpoTGdhqYP0gRLAYyEDyUTwj2Ft7hBQv+B",
	"uWLLRfE3YKVZ0oT6hy1N6CexbJ9/Ztzv88nr4XbFeMkWJRymygeDiaKdt70/EB+bg6MJkzdsneJa6JEu",
	"Xp7yUcU2j6gZGDoXF+bHN936XhgRwTBmRUpnRXO9fqRoZ71Gbe+kFWYmcStQehYkcFw0dEUdQQEzgCZ1",
	"CAu8JNpnYCANUOlgthUrrqSo0MYEq/VSGm8aDRbMIGe29AJpgsSMqPI5OSKblsA2oR0T0D5wAdpwh7Xu",
	"rXJY7QlSKbKJqf3pp6g265KJmeJ1uyMx+N2aKcFFEYUEkwwaEtpIBu7oZD8DMYncB7m1drwv/D9CKqsK",
	"RNbi11luEXKKNyHGS/1tgAE2XBsdjz8Hg9OLIsCpnhmVVFTqnBVCanhdyO7C+WmQacSX3+EwB/v8iHkU",
	"D/PRW1OpRYBb5o/jR/e4bxdOIkT7ywF+/AEjXTADhVTbY0djLrYK7prlGAyk1nxRwh2zGk5ybUR+WDCa",
	"bR88pIobnrLSIcgvEtFKxYWMYxBtiwK0gWyqheOH26pianvc8lvh9AjuPo9JOpYiXGLo1/bNL0TmxPk8",
	"FwWppOBGIhmkEz9hIiO1AkeU5gb0JU0iRdeJddM0LsasMiw6Bbv4KPWUSgVTtm+LQkHBDBC/jGhcR9gK",
	"FCsgI7mSVcc7QZBqHb8TmNEVGNfX0RJjhI50zdIIQR+ZKsCQdgVZL0FBXxPasPSZKNA886KPQP1+PNQR",
	"ZTeGSnxhf2Fr4kOpJgvIUQK8lzHxkBdmyJ7C+mwPKuuozbZ9qEikzuJY+Sz5bn+zYsRZszBK/aAF8q3l",
	"nWtjoZOnmFttvLxr2xynuEbaxyAnJepDPR2pMlAzofjJ9bT7xFg9qDpBZL6KU1YI/+TaRZA5fJo3NRsW",
	"x/Wgp7dHuZ6FvoCSrjAOBMQUP85IPSLfVayAB+uU/AhaWpXC3600WB9/ALOW6vlBljxFRT++vb2jCX0y",
	"EqPQXcm0dgVpWd0tmUJi7gGZBuGW+6ohYE+a0I+8AmmNq1yfhVyLqMUMS45JjPikQZFayRXPICOy9tHB",
	"xUOzBLLm/2Yqm0Z+BCGP3nL7xYdRFpL9Jez74NONsHyvAFXGtObalxmLrYwyYlzI/NCPqdNWMCst6H+x",
	"qpxy+sjWBGVL/CIiV6AUz6DjfrF1PFsN6nJei2cA8s4JcF7usmdBuAf9PnXdxROdGepfZ8eL/VDoUDQe",
	"9AmHjaEnH35oU5b52OFaRP4x3iOiCcUyawXuQxews2lvyC/8JHi3xwE/fHJRZT+6Twc97oOa71b2E8O0",
	"/31SF//7tMaH7emTCDxz5/q/2IJ2Da1jRz/iIm80r9C2RiByYtd+PK9pCWpkObCZ/gEHnLbr2Jy7baS4",
	"fv4FVlD2Q0Ip1y6YZNxWNKFLXizjlZ5n7iNUdRkau4d09TRaHgLffGNFCcQdMS719qTmoJiI202/FaBa",
	"0f0cwOrns6LNzKEd/auYJm+XPDQxS2ZIZbUhCyBtyCM5V9rEypcDM79vtKtT0O/cmcwBOBpTrAsNeztd",
	"uVSxwvNnfE1c6CGwAkF4TsIUnKfuPQdNmAICmyWziMl6WKgH6aqA5Ybb34NGbsIBuObPRFbcECMRV5GA",
	"FMkClmzFpXVAqwcHrevBtAQdGXGNbKT2YIf4BQTrY5W56lcRZjNuSG1VLXW0nt7tk/BTW4hMvWcVEcE7",
	"kXGELBprerMERZgYiXhLuCYhCZZbgg6R2XKfpBcsfZZ53rPP4YF3fiMS1pEMSrYlXBDtv2hqfcS2AjbG",
	"kzDubuyx85Jpc2sMVLW5jfSTsAbRhlU1MivcEZXUeESKJHlmmf+ehPQ0OPnoEKvF1sODf2HakNwDZxJg",
	"oQ8PRvGiADRC1nF6ZNQ13Pu9z+DEp2oi8yEfmtSgKm7GrOwPAI2vzEz0rkzaJRSV5V7PlLxT7tjS1rws",
	"MVq2YpkvfrVPQB/2CYaVCli2JeBQ20z5HPG8cdHIM3d1p3WaQT+gDVrRyPE0zedDn+7maS+anY1afhGB",
	"lsA0NOP0F5S4kfmIXxpLEK7sCQhr/0TkhQXHy+ZxscnacdL3Fktu7HgS3v0iF3vFf0x52lZ+Unss4Led",
	"dWiqF7JmmoQdQre5lWY86p9w+6uPwQfN11Y8UxHvXFcmlxHnho25KECAh0X9nnS/W0zWUj3npVxjXm97",
	"Jw+yZOr+7cU/Scb0ciGZyi5/Fw++w6IJdDMK4nvGXIqE1KEST3oCM4qlz+5dGDAZnurETSW8/xG0BN/6",
	"vvxdtJf6bmhHw/uO9L4pktuHd2T1hvYGkfT68ofLawfsahCs5vSG/nh5ffkjljXMLJ25XXWiuMIwe5GH",
	"64/SO1ZLECqN3tZ1uW1Gb15hoE3T7D7LNc7RBcXd0DCMsuDttrtO+ub6+vynB/eMXCW9DVJqIQC6QGk8",
	"2A89w/ghLdVXwxuwu/4QLXTgoYewHPbEys5r2kG/xoLQ9TxiuHT79PXprRGpKSCiTN836o3Y6CsKNnrZ",
	"Yyrc+8aBSLg0mdvybJL1m88dDSLaRPdPS0y+KiLeoIH97tIMvkMz9JU8ZnxB4Du7zGS6H1NrMzHvCtzz",
	"aTWcTxjx05JhSNcG6hBhjVVi4Elh6u3C7US9DUraq91+PmftzcPz6zcGeWbp+M0rkbBfz4OMxNIU6nNq",
	"2lFB/D1+W8H+LM7NEsPn4CXm471Kvvra4o3dVdvDjKv9oy86HJp3mVSxCgwoTW9++3pIHuEIwjMQhufc",
	"9UU4LsNsTJt7RwPoM1Rx0lPXGD59fh3jGzRkdsHsXsnK4uOEiJk9+grt3PYV2HSmU/ko0bSVMOWmz0Ku",
	"S8gKDDVtqRYW+KQcVDfPzrppcDQ9/xXMQCD/a7b2SulkthE0LSIvRqcATNc8Iga0kJ+uf/o+/2oUCnIi",
	"pCG5tOKc9mkUh9WIx2Zwc8wEm+I2HtW6266vlMWm942/M06J3OeNaA9/J6HIPJvi3lpeZpOMJBUJ/ReX",
	"nHwJnXUAuLnWhuDFalDEd3IuPdka1KoJBFaV9IZesZpfrX6gu8+7/wQAAP//1/CiN383AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
