apiVersion: polardbx.aliyun.com/v1
kind: XStoreBackup
metadata:
  name: test-pitr-dn-backup-1
  namespace: default
spec:
  xstore:
    name: test-pitr-zw6s-dn-0
    uid: ""  # 自动填充
  engine: galaxy
  storageProvider:
    storageName: local
    sink: local://default/test-pitr-dn-backup-1
