apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /home/master1/.minikube/ca.crt
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube-file
current-context: minikube-file
users:
- name: minikube
  user:
    client-certificate: /home/master1/.minikube/profiles/minikube/client.crt
    client-key: /home/master1/.minikube/profiles/minikube/client.key
