apiVersion: polardbx.aliyun.com/v1
kind: PolarDBXCluster
metadata:
  name: mycluster
  namespace: default
spec:
  topology:
    nodes:
      cn:
        replicas: 1
        template:
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      dn:
        replicas: 1
        template:
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      gms:
        template:
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
