apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/master1/桌面/polardbx-operator/kubeconfig-original/ca.crt
    server: https://192.168.49.2:8443
    extensions:
    - name: cluster_info
      extension:
        last-update: Fri, 10 Oct 2025 11:25:00 CST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
    namespace: default
    extensions:
    - name: context_info
      extension:
        last-update: Fri, 10 Oct 2025 11:25:00 CST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/master1/桌面/polardbx-operator/kubeconfig-original/client.crt
    client-key: /home/master1/桌面/polardbx-operator/kubeconfig-original/client.key
