apiVersion: v1
kind: Service
metadata:
  name: polardbx-ui-backend
  labels:
    app: polardbx-ui-backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: polardbx-ui-backend

